import { publicContent } from "./publicContent";
// Multilingual content: Persian (fa, default, RTL), English (en, LTR), Arabic (ar, RTL)
export const languages = {
  fa: { code: "fa", name: "فارسی", flag: "🇮🇷", dir: "rtl", label: "Persian" },
  en: { code: "en", name: "English", flag: "🇬🇧", dir: "ltr", label: "English" },
  ar: { code: "ar", name: "العربية", flag: "🇸🇦", dir: "rtl", label: "Arabic" },
};

export const defaultLang = "fa";

export const translations = {
  fa: {
    // nav
    nav: { home: "خانه", about: "درباره پزشک", services: "خدمات", qualifications: "تحصیلات و مدارک", clinic: "کلینیک", appointment: "نوبت‌گیری", pricing: "محاسبه هزینه", contact: "تماس", login: "ورود", register: "ثبت‌نام", dashboard: "پنل کاربری", logout: "خروج" },
    // hero
    hero: { badge: "جراحی استخوان و مفاصل", title: "دکتر فاضل صداقت", specialty: "جراح و متخصص استخوان و مفاصل (ارتوپدی)", intro: "با بیش از ۳۳ سال تجربه در ارزیابی و درمان بیماری‌های اسکلتی‌عضلانی، از کمردرد و آرتروز تا آسیب‌های مفصلی و تعویض مفصل، درمان بر پایه تشخیص دقیق، تصمیم‌گیری علمی و همراهی مسئولانه با بیمار پیش می‌رود.", book: "دریافت نوبت", calc: "محاسبه هزینه ویزیت", careCard: "رویکرد دقیق ارتوپدی", bookCard: "مشاوره برای درد و اختلالات حرکتی" },
    // stats
    stats: { years: "تجربه در ارتوپدی", patients: "تشخیص و درمان", consults: "مراقبت تخصصی", certs: "پیگیری درمان", note: "" },
    // sections
    sections: { servicesTitle: "خدمات تخصصی ارتوپدی", servicesSub: "ارزیابی، درمان و پیگیری مشکلات استخوان، مفصل و ستون فقرات", whyTitle: "چرا دکتر فاضل صداقت؟", whySub: "تجربه بالینی، تشخیص دقیق و برنامه درمانی متناسب با شرایط هر بیمار", eduTitle: "تحصیلات و گواهینامه‌ها", eduSub: "مسیر علمی و حرفه‌ای", galleryTitle: "گالری کلینیک", gallerySub: "فضایی آرام و مجهز برای مراجعین", insuranceTitle: "بیمه‌های پذیرفته‌شده", insuranceSub: "محاسبه دقیق هزینه بر اساس بیمه", ctaTitle: "نوبت خود را رزرو کنید", ctaSub: "برای ارزیابی درد یا پیگیری درمان، وقت خود را رزرو کنید", testimonialsTitle: "تجربه بیماران", testimonialsSub: "نظرات واقعی مراجعین", faqTitle: "سوالات متداول", faqSub: "پاسخ به پرسش‌های رایج", locationTitle: "موقعیت کلینیک", locationSub: "آدرس و راه‌های دسترسی", contactTitle: "تماس با کلینیک", contactSub: "برای هماهنگی و دریافت راهنمایی با ما تماس بگیرید" },
    // appointment
    appointment: { title: "رزرو نوبت", step1: "انتخاب خدمت", step2: "انتخاب تاریخ", step3: "انتخاب ساعت", step4: "انتخاب بیمه", step5: "اطلاعات بیمار", step6: "خلاصه هزینه", step7: "تأیید نهایی", service: "خدمت", date: "تاریخ", time: "ساعت", insurance: "بیمه", selfPay: "آزاد (بدون بیمه)", patientInfo: "اطلاعات بیمار", basePrice: "مبلغ پایه", coverage: "سهم بیمه", final: "مبلغ قابل پرداخت", confirm: "تأیید و ثبت نوبت", success: "نوبت شما با موفقیت ثبت شد", appointmentId: "کد نوبت", selectService: "یک خدمت انتخاب کنید", selectDate: "یک تاریخ انتخاب کنید", selectTime: "یک ساعت انتخاب کنید", selectInsurance: "بیمه خود را انتخاب کنید", noSlots: "ساعتی برای این تاریخ موجود نیست", prev: "قبلی", next: "بعدی", firstName: "نام", lastName: "نام خانوادگی", mobile: "شماره موبایل", email: "ایمیل", notes: "توضیحات" },
    // pricing
    pricing: { title: "محاسبه هزینه ویزیت", service: "خدمت", insurance: "بیمه", base: "مبلغ پایه", deduction: "کسر بیمه", final: "مبلغ نهایی", currency: "تومان", calculate: "محاسبه", selfPay: "آزاد" },
    // auth
    auth: { login: "ورود", register: "ثبت‌نام", email: "ایمیل", password: "رمز عبور", firstName: "نام", lastName: "نام خانوادگی", mobile: "شماره موبایل", forgot: "فراموشی رمز عبور؟", noAccount: "حساب کاربری ندارید؟", haveAccount: "قبلاً ثبت‌نام کرده‌اید؟", loginBtn: "ورود", registerBtn: "ثبت‌نام", welcome: "خوش آمدید" },
    // dashboard
    dash: { home: "خانه", appointments: "نوبت‌ها", history: "پرونده پزشکی", prescriptions: "نسخه‌ها", medications: "داروها", documents: "مدارک", profile: "پروفایل", notifications: "اعلان‌ها", overview: "نمای کلی", today: "امروز", patients: "بیماران", revenue: "درآمد", reports: "گزارش‌ها", settings: "تنظیمات", nextAppt: "نوبت بعدی", prevAppts: "نوبت‌های قبلی", visits: "بازدیدها", activeMeds: "داروهای فعال", myAppts: "نوبت‌های من", myHistory: "پرونده پزشکی من", myPrescriptions: "نسخه‌های من", myMedications: "داروهای من", myDocuments: "مدارک من", myProfile: "پروفایل من" },
    // common
    common: { loading: "در حال بارگذاری...", save: "ذخیره", cancel: "انصراف", edit: "ویرایش", delete: "حذف", search: "جستجو", close: "بستن", back: "بازگشت", status: "وضعیت", date: "تاریخ", time: "ساعت", doctor: "پزشک", patient: "بیمار", price: "مبلغ", currency: "تومان", confirmed: "تأیید شده", requested: "در انتظار", cancelled: "لغو شده", completed: "تکمیل شده", noShow: "عدم حضور", noData: "اطلاعاتی موجود نیست", book: "دریافت نوبت", call: "تماس", directions: "مسیریابی" },
    footer: { rights: "تمامی حقوق محفوظ است", quickLinks: "دسترسی سریع", contact: "تماس", address: "آدرس", hours: "ساعات پذیرش" },
    announcement: "پذیرش نوبت جدید آغاز شد — همین حالا وقت خود را رزرو کنید",
  },
  en: {
    nav: { home: "Home", about: "About Doctor", services: "Services", qualifications: "Qualifications", clinic: "Clinic", appointment: "Appointment", pricing: "Price Calculator", contact: "Contact", login: "Login", register: "Register", dashboard: "Dashboard", logout: "Logout" },
    hero: { badge: "Orthopedic Surgery", title: "Dr. Fazel Sedaghat", specialty: "Orthopedic Surgeon · Doctor of Medicine", intro: "With more than 33 years of experience in musculoskeletal care, from back pain and osteoarthritis to joint injuries and joint replacement, treatment is guided by accurate diagnosis, sound clinical judgment and responsible follow-up.", book: "Book Appointment", calc: "Calculate Visit Price", careCard: "Focused Orthopedic Care", bookCard: "Consultation for pain and mobility problems" },
    stats: { years: "Orthopedic expertise", patients: "Assessment and treatment", consults: "Specialist care", certs: "Treatment follow-up", note: "" },
    sections: { servicesTitle: "Orthopedic Services", servicesSub: "Assessment, treatment and follow-up for bones, joints and the spine", whyTitle: "Why Dr. Fazel Sedaghat?", whySub: "Clinical experience, careful diagnosis and a plan tailored to each patient", eduTitle: "Education & Certifications", eduSub: "Academic and professional journey", galleryTitle: "Clinic Gallery", gallerySub: "A calm, well-equipped space for patients", insuranceTitle: "Accepted Insurance", insuranceSub: "Accurate cost calculation based on your insurance", ctaTitle: "Book Your Appointment", ctaSub: "Reserve a visit for pain assessment or treatment follow-up", testimonialsTitle: "Patient Experiences", testimonialsSub: "Real reviews from our patients", faqTitle: "Frequently Asked Questions", faqSub: "Answers to common questions", locationTitle: "Clinic Location", locationSub: "Address and directions", contactTitle: "Contact the Clinic", contactSub: "Contact us for scheduling and guidance" },
    appointment: { title: "Book Appointment", step1: "Choose Service", step2: "Choose Date", step3: "Choose Time", step4: "Choose Insurance", step5: "Patient Info", step6: "Price Summary", step7: "Confirmation", service: "Service", date: "Date", time: "Time", insurance: "Insurance", selfPay: "Self-Pay", patientInfo: "Patient Information", basePrice: "Base Price", coverage: "Insurance Coverage", final: "Amount to Pay", confirm: "Confirm & Book", success: "Your appointment was booked successfully", appointmentId: "Appointment ID", selectService: "Select a service", selectDate: "Select a date", selectTime: "Select a time", selectInsurance: "Select your insurance", noSlots: "No slots available for this date", prev: "Previous", next: "Next", firstName: "First Name", lastName: "Last Name", mobile: "Mobile", email: "Email", notes: "Notes" },
    pricing: { title: "Visit Price Calculator", service: "Service", insurance: "Insurance", base: "Base Price", deduction: "Insurance Deduction", final: "Final Amount", currency: "Toman", calculate: "Calculate", selfPay: "Self-Pay" },
    auth: { login: "Login", register: "Register", email: "Email", password: "Password", firstName: "First Name", lastName: "Last Name", mobile: "Mobile", forgot: "Forgot password?", noAccount: "Don't have an account?", haveAccount: "Already have an account?", loginBtn: "Login", registerBtn: "Register", welcome: "Welcome" },
    dash: { home: "Home", appointments: "Appointments", history: "Medical History", prescriptions: "Prescriptions", medications: "Medications", documents: "Documents", profile: "Profile", notifications: "Notifications", overview: "Overview", today: "Today", patients: "Patients", revenue: "Revenue", reports: "Reports", settings: "Settings", nextAppt: "Next Appointment", prevAppts: "Previous Appointments", visits: "Visits", activeMeds: "Active Medications", myAppts: "My Appointments", myHistory: "My Medical History", myPrescriptions: "My Prescriptions", myMedications: "My Medications", myDocuments: "My Documents", myProfile: "My Profile" },
    common: { loading: "Loading...", save: "Save", cancel: "Cancel", edit: "Edit", delete: "Delete", search: "Search", close: "Close", back: "Back", status: "Status", date: "Date", time: "Time", doctor: "Doctor", patient: "Patient", price: "Amount", currency: "Toman", confirmed: "Confirmed", requested: "Pending", cancelled: "Cancelled", completed: "Completed", noShow: "No-show", noData: "No data available", book: "Book Appointment", call: "Call", directions: "Directions" },
    footer: { rights: "All rights reserved", quickLinks: "Quick Links", contact: "Contact", address: "Address", hours: "Reception hours" },
    announcement: "New appointments are now open — book your visit today",
  },
  ar: {
    nav: { home: "الرئيسية", about: "عن الطبيب", services: "الخدمات", qualifications: "المؤهلات", clinic: "العيادة", appointment: "حجز موعد", pricing: "حساب التكلفة", contact: "اتصل", login: "تسجيل الدخول", register: "تسجيل", dashboard: "لوحة التحكم", logout: "تسجيل الخروج" },
    hero: { badge: "جراحة العظام والمفاصل", title: "د. فاضل صداقت", specialty: "اختصاصي جراحة العظام والمفاصل · دكتوراه مهنية في الطب", intro: "خبرة تتجاوز 33 عامًا في تقييم وعلاج آلام الظهر والمفاصل والفصال العظمي والإصابات ومتابعة حالات استبدال المفصل، مع خطة علاجية مبنية على التشخيص الدقيق والمتابعة المسؤولة.", book: "حجز موعد", calc: "حساب تكلفة الزيارة", careCard: "رعاية متخصصة للعظام", bookCard: "استشارة لآلام الحركة والمفاصل" },
    stats: { years: "خبرة في جراحة العظام", patients: "تشخيص وعلاج", consults: "رعاية تخصصية", certs: "متابعة العلاج", note: "" },
    sections: { servicesTitle: "خدمات جراحة العظام", servicesSub: "تقييم وعلاج ومتابعة مشكلات العظام والمفاصل والعمود الفقري", whyTitle: "لماذا د. فاضل صداقت؟", whySub: "خبرة سريرية وتشخيص دقيق وخطة تناسب حالة كل مريض", eduTitle: "التعليم والمؤهلات", eduSub: "المسار الأكاديمي والمهني", galleryTitle: "معرض العيادة", gallerySub: "مساحة هادئة ومجهزة للمرضى", insuranceTitle: "التأمينات المقبولة", insuranceSub: "حساب دقيق للتكلفة بناءً على التأمين", ctaTitle: "احجز موعدك", ctaSub: "احجز زيارتك لتقييم الألم أو متابعة العلاج", testimonialsTitle: "تجارب المرضى", testimonialsSub: "آراء حقيقية من مرضانا", faqTitle: "الأسئلة الشائعة", faqSub: "إجابات للأسئلة المتكررة", locationTitle: "موقع العيادة", locationSub: "العنوان والاتجاهات", contactTitle: "اتصل بالعيادة", contactSub: "تواصل معنا للمواعيد والإرشاد" },
    appointment: { title: "حجز موعد", step1: "اختر الخدمة", step2: "اختر التاريخ", step3: "اختر الوقت", step4: "اختر التأمين", step5: "بيانات المريض", step6: "ملخص التكلفة", step7: "التأكيد النهائي", service: "الخدمة", date: "التاريخ", time: "الوقت", insurance: "التأمين", selfPay: "مخصص (بدون تأمين)", patientInfo: "بيانات المريض", basePrice: "السعر الأساسي", coverage: "مساهمة التأمين", final: "المبلغ المستحق", confirm: "تأكيد وحجز", success: "تم حجز موعدك بنجاح", appointmentId: "رمز الموعد", selectService: "اختر خدمة", selectDate: "اختر تاريخًا", selectTime: "اختر وقتًا", selectInsurance: "اختر تأمينك", noSlots: "لا توجد مواعيد متاحة لهذا التاريخ", prev: "السابق", next: "التالي", firstName: "الاسم", lastName: "اسم العائلة", mobile: "الجوال", email: "البريد الإلكتروني", notes: "ملاحظات" },
    pricing: { title: "حاسبة تكلفة الزيارة", service: "الخدمة", insurance: "التأمين", base: "السعر الأساسي", deduction: "خصم التأمين", final: "المبلغ النهائي", currency: "تومان", calculate: "احسب", selfPay: "مخصص" },
    auth: { login: "تسجيل الدخول", register: "تسجيل", email: "البريد الإلكتروني", password: "كلمة المرور", firstName: "الاسم", lastName: "اسم العائلة", mobile: "الجوال", forgot: "نسيت كلمة المرور؟", noAccount: "ليس لديك حساب؟", haveAccount: "لديك حساب بالفعل؟", loginBtn: "دخول", registerBtn: "تسجيل", welcome: "مرحبًا" },
    dash: { home: "الرئيسية", appointments: "المواعيد", history: "التاريخ الطبي", prescriptions: "الوصفات", medications: "الأدوية", documents: "المستندات", profile: "الملف الشخصي", notifications: "الإشعارات", overview: "نظرة عامة", today: "اليوم", patients: "المرضى", revenue: "الإيرادات", reports: "التقارير", settings: "الإعدادات", nextAppt: "الموعد التالي", prevAppts: "المواعيد السابقة", visits: "الزيارات", activeMeds: "الأدوية النشطة", myAppts: "مواعيدي", myHistory: "تاريخي الطبي", myPrescriptions: "وصفاتي", myMedications: "أدويتي", myDocuments: "مستنداتي", myProfile: "ملفي الشخصي" },
    common: { loading: "جارٍ التحميل...", save: "حفظ", cancel: "إلغاء", edit: "تعديل", delete: "حذف", search: "بحث", close: "إغلاق", back: "رجوع", status: "الحالة", date: "التاريخ", time: "الوقت", doctor: "الطبيب", patient: "المريض", price: "المبلغ", currency: "تومان", confirmed: "مؤكد", requested: "قيد الانتظار", cancelled: "ملغى", completed: "مكتمل", noShow: "لم يحضر", noData: "لا توجد بيانات", book: "حجز موعد", call: "اتصال", directions: "الاتجاهات" },
    footer: { rights: "جميع الحقوق محفوظة", quickLinks: "روابط سريعة", contact: "اتصل", address: "العنوان", hours: "ساعات الاستقبال" },
    announcement: "تم فتح حجز المواعيد الجديدة — احجز زيارتك الآن",
  },
};

for (const lang of Object.keys(publicContent)) {
  Object.assign(translations[lang], publicContent[lang]);
}

export function getNested(obj, path) {
  return path.split(".").reduce((acc, k) => (acc && acc[k] !== undefined ? acc[k] : undefined), obj);
}
